"""Build a self-contained notebook from public source; no data or model uploads."""
import hashlib
import json
from pathlib import Path
import uuid

ROOT=Path(__file__).resolve().parents[1]


def cell(kind, source):
    item={'cell_type':kind,'id':uuid.uuid5(uuid.NAMESPACE_URL,source).hex[:12],
          'metadata':{},'source':source.splitlines(keepends=True)}
    if kind=='code': item.update(execution_count=None,outputs=[])
    return item


def build():
    files={}
    for folder in ['src','scripts','tests','docs']:
        for path in sorted((ROOT/folder).rglob('*')):
            if path.is_file() and path.suffix in {'.py','.md'} and '__pycache__' not in path.parts:
                if path.name=='build_kaggle_notebook.py': continue
                files[str(path.relative_to(ROOT))]=path.read_text()
    for name in ['pyproject.toml','LICENSE']:
        files[name]=(ROOT/name).read_text()
    hashes={name:hashlib.sha256(value.encode()).hexdigest() for name,value in files.items()}
    embedded='SOURCE_FILES = '+repr(files)+'\nSOURCE_HASHES = '+repr(hashes)+'\n'
    bootstrap='''from pathlib import Path
import hashlib, json, os, subprocess, sys
WORK = Path('/kaggle/working') if Path('/kaggle/working').exists() else Path.cwd()
PROJECT = WORK / 'mallorn_project'
PROJECT.mkdir(parents=True, exist_ok=True)
for name, source in SOURCE_FILES.items():
    path = PROJECT / name
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() != source:
        raise RuntimeError(f'Existing source differs: {name}. Use a new work directory.')
    path.write_text(source)
    assert hashlib.sha256(path.read_bytes()).hexdigest() == SOURCE_HASHES[name]
(PROJECT / 'source_manifest.json').write_text(json.dumps(SOURCE_HASHES, indent=2))
ENV = dict(os.environ, MPLCONFIGDIR=str(PROJECT/'artifacts/mpl'), OPENBLAS_NUM_THREADS='1', MALLORN_THREADS='2')
import importlib.metadata, tomllib
requirements = tomllib.loads(SOURCE_FILES['pyproject.toml'])['project']['dependencies']
def versions_match():
    try:
        return all(importlib.metadata.version(r.split('==')[0]) == r.split('==')[1] for r in requirements)
    except importlib.metadata.PackageNotFoundError:
        return False
PYTHON = Path(sys.executable)
if not versions_match():
    PYTHON = PROJECT / '.venv/bin/python'
    if not PYTHON.exists():
        subprocess.run([sys.executable, '-m', 'venv', '--without-pip', '--system-site-packages', str(PROJECT/'.venv')], check=True)
    subprocess.run([sys.executable, '-m', 'pip', '--python', str(PYTHON), 'install', '--no-cache-dir', '-q', *requirements], check=True, env=ENV)
ENV['PYTHONPATH'] = str(PROJECT/'src')
def command(*args):
    subprocess.run([str(PYTHON), *map(str,args)], cwd=PROJECT, env=ENV, check=True)
print(f'Checked {len(SOURCE_FILES)} source files; pinned dependencies installed.')
'''
    cells=[cell('markdown','''# MALLORN: Reproducible TDE Classification

**Ehsan Cheraghi — Python, astronomical time series and rare-event machine learning**

Source: https://github.com/Ehsan-Ch/mallorn-tde-classifier

This notebook contains the project source, a synthetic software check, and optional
official-data training. It does not submit predictions to a competition.

## Recorded results (historical, not generated by this notebook run)

| Evaluation | F1 |
| --- | ---: |
| Kaggle private — completed late submission, 4 October 2026 | **0.6648** |
| Kaggle public — same prediction file | 0.6825 |
| Original nested local baseline | 0.5254 |
| Frozen improvement: development / reserved audit | 0.6912 / 0.5833 |

The top private benchmark was 0.6824. This project does **not** claim to beat it.
Later local selection scores are not comparable private-test scores. The recovered
cycle-5 method is included, but its original trained artifacts were lost in a
workspace rollback; see the repository recovery note. There are no model weights,
raw competition data or fabricated execution outputs embedded here.

## Method

Per-band statistics, dust correction, rest-frame timing, common-phase colours,
GP/thermal and flare features; LightGBM/CatBoost models, auxiliary class targets,
training-fold feature selection, nested evaluation and F1 threshold selection.
Inspired by the published second- and third-place solutions, independently implemented.

CPU is sufficient. Enable Internet for the initial installation. Add the official
MALLORN competition data through **Add Input** after accepting its rules if you
want official training. The default run performs only a short software check.
'''),cell('code',embedded+bootstrap),cell('markdown','''## 1. Software check

The following run uses invented light curves to test software behavior.
Its score is **not competition performance**. A completed matching check is reused.
'''),cell('code','''SMOKE = PROJECT / 'artifacts/kaggle_smoke'
receipt = SMOKE / 'completed_source_hashes.json'
if receipt.exists():
    assert json.loads(receipt.read_text()) == SOURCE_HASHES
    print('Reusing a completed matching synthetic software check.')
else:
    if SMOKE.exists() and any(SMOKE.iterdir()):
        raise RuntimeError('An interrupted smoke directory exists. Inspect it and choose a new output name.')
    command('scripts/notebook_smoke.py','--output',SMOKE)
    receipt.write_text(json.dumps(SOURCE_HASHES,indent=2))
print('Synthetic software check completed. This is not a Kaggle score.')
'''),cell('markdown','''## 2. Locate attached official data

This reads the competition input only. Official fitting is opt-in below.
'''),cell('code','''INPUT = Path('/kaggle/input')
matches = sorted(INPUT.rglob('train_log.csv')) if INPUT.exists() else []
DATA = next((p.parent for p in matches if (p.parent/'test_log.csv').exists() and (p.parent/'sample_submission.csv').exists()), None)
print('Official data:', DATA if DATA else 'Not attached. Add MALLORN via Add Input to enable training.')
'''),cell('markdown','''## 3. Optional official nested baseline

Set `RUN_OFFICIAL = True` to train the original nested-validation workflow.
This writes predictions locally but does not submit them. The output folder
must be fresh; a completed matching run is reused by its receipt.
'''),cell('code','''RUN_OFFICIAL = False
OFFICIAL = PROJECT / 'artifacts/official_001'
if RUN_OFFICIAL:
    if DATA is None: raise RuntimeError('Attach the official MALLORN competition data first.')
    official_receipt = OFFICIAL/'completed_source_hashes.json'
    if official_receipt.exists():
        assert json.loads(official_receipt.read_text()) == SOURCE_HASHES
        print('Reusing completed matching official run.')
    else:
        command('-m','mallorn.cli','run','--data',DATA,'--output',OFFICIAL,'--threads','2')
        official_receipt.write_text(json.dumps(SOURCE_HASHES,indent=2))
else:
    print('Official model fitting is disabled for this publication run.')
'''),cell('markdown','''## 4. Optional physical features and research code

After an official baseline, the builders can compute GP/thermal, flare and
physical feature views. A symlink references attached data without copying it.
Original cycles 2–4 and the recovered cycle-5 runner are included under `scripts/`.
Historical replay requires the original private checkpoint/reference artifacts;
the public notebook does not invent them. See `docs/RESUME_RESEARCH.md`.
'''),cell('code','''BUILD_PHYSICAL_FEATURES = False
if BUILD_PHYSICAL_FEATURES:
    if DATA is None or not (OFFICIAL/'features.csv').exists():
        raise RuntimeError('Complete the official baseline first.')
    (PROJECT/'data').mkdir(exist_ok=True)
    target = PROJECT/'data/mallorn'
    if not target.exists(): target.symlink_to(DATA, target_is_directory=True)
    if target.resolve() != DATA.resolve(): raise RuntimeError('Data link points at another dataset.')
    for mode in ('train','test'):
        command('scripts/build_physics_features.py','--mode',mode,'--workers','2')
        command('scripts/build_morphology_features.py','--mode',mode)
        command('scripts/build_physical_view.py','--mode',mode)
else:
    print('Physical feature extraction is disabled for this publication run.')
'''),cell('markdown','''## Resume and limitations

Saved Kaggle versions preserve the notebook; export/download output checkpoints
before ending a session if you need them later. Local notebook folders alone
are not guaranteed to survive a new runtime. Source hashes and model receipts
must match before reusing artifacts. A usage reset cannot be detected by Python;
the assistant resumes publication after the user says **continue** and checks
`publication/state.json` on GitHub before creating or updating remote resources.

Object-level folds cannot establish source-template independence. Labels have
been repeatedly reused for later development selection. Accurate training
redshifts differ from noisy test redshifts. F1 thresholds may transfer poorly.

Code: MIT. Official data remain under Kaggle competition rules. Created with
OpenAI Codex assistance for Ehsan Cheraghi. Method references and distinctions:
https://github.com/Ehsan-Ch/mallorn-tde-classifier/blob/main/docs/SOURCES.md
''')]
    notebook={'cells':cells,'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},
        'language_info':{'name':'python','version':'3.12'},'kaggle':{'accelerator':'none','isInternetEnabled':True}},'nbformat':4,'nbformat_minor':5}
    dest=ROOT/'notebooks/mallorn_research.ipynb'
    dest.parent.mkdir(exist_ok=True)
    dest.write_text(json.dumps(notebook,indent=1)+'\n')
    (ROOT/'publication/notebook_manifest.json').write_text(json.dumps({'notebook_sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),
        'embedded_source_hashes':hashes,'cells':len(cells),'outputs_prepopulated':False},indent=2)+'\n')
    print(f'Wrote {dest}; {len(files)} embedded source files, {len(cells)} cells')


if __name__=='__main__': build()
